analyzevmcore supports local directories bsc#1186397

diff --git a/bin/analyzevmcore b/bin/analyzevmcore
--- a/bin/analyzevmcore
+++ b/bin/analyzevmcore
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-SVER='1.33'
-SDATE="2020 03 13"
+SVER='1.38'
+SDATE="2021 05 25"
 SNAME="analyzevmcore"
 
 # --------------------------------------------------------------------- #
@@ -11,7 +11,7 @@ SNAME="analyzevmcore"
 #  Please submit bug fixes or comments via:                             #
 #    http://en.opensuse.org/Supportutils#Reporting_Bugs                 #
 #                                                                       #
-#  Copyright (C) 1999-2020 SUSE Linux Products GmbH, Nuernberg, Germany #
+#  Copyright (C) 1999-2021 SUSE Linux Products GmbH, Nuernberg, Germany #
 #                                                                       #
 # --------------------------------------------------------------------- #
 #                                                                       #
@@ -52,6 +52,8 @@ SNAME="analyzevmcore"
 # --------------------------------------------------------------------- #
 # Changes:                                                              #
 #                                                                       #
+# 1.38 Release                                                          #
+#    - Fixed local directory KDUMP_SAVEDIR support                      #
 # 1.33 Release                                                          #
 #    - Changed filename prefix from nts_ to scc_ with FILENAME_PREFIX   #
 #    - Processes all available crash dumps                              #
@@ -224,7 +226,7 @@ extractdebug()
 	DBGRPM_NAME=$($BASENAME_BIN $DBGRPM)
 	DBGRPM_NAME=${DBGRPM_NAME#*-*-}
 	if ! [ "${DBGRPM_NAME:0:9}" = "debuginfo" -a "${DBGRPM_NAME:(-4)}" = ".rpm" ]; then
-		echo "    Invalid RPM specied!"
+		echo "    Invalid RPM specified!"
 		echo "    Please specify a valid kernel-*-debuginfo.rpm file with the -d parameter,"
 		echo "    or install the kernel-*-debuginfo rpm, and do not use the -d parameter."
 		exit -1
@@ -530,15 +532,18 @@ if [[ "${CRASH_VER:0:1}" < "5" ]]; then
 	CRASHV4="1"
 fi
 
-if [ -z "$COREDIR" ]; then
+if [[ -z "$COREDIR" ]]; then
 	#Source /etc/sysconfig/kdump
-	if [ -e "/etc/sysconfig/kdump" ]; then
+	if [[ -e "/etc/sysconfig/kdump" ]]; then
 		. /etc/sysconfig/kdump
-		if [ "${KDUMP_SAVEDIR:0:8}" = "file:///" ]; then
+		if [[ "${KDUMP_SAVEDIR:0:8}" = "file:///" ]]; then
 			KDUMP_SAVEDIR=${KDUMP_SAVEDIR:7}
+		elif [[ "${KDUMP_SAVEDIR:0:1}" = "/" ]]; then
+			:
 		else
 			echo "Unsupported KDUMP_SAVEDIR specified in /etc/sysconfig/kdump!"
-			echo "  Supported syntax:  file:///var/crash"
+			echo "  Only local directories are supported"
+			echo '  Supported syntax:  [file://]/var/crash'
 			echo "  Current setting:   $KDUMP_SAVEDIR"
 			echo
 			exit -1
@@ -548,8 +553,8 @@ if [ -z "$COREDIR" ]; then
 	fi
 fi
 
-if [ -z "$COREDIR" ]; then
-	if ! [ -d "$KDUMP_SAVEDIR" ]; then
+if [[ -z "$COREDIR" ]]; then
+	if ! [[ -d "$KDUMP_SAVEDIR" ]]; then
 		echo "Invalid KDUMP_SAVEDIR specified in /etc/sysconfig/kdump! ($KDUMP_SAVEDIR)"
 		echo
 		exit -1
@@ -557,7 +562,7 @@ if [ -z "$COREDIR" ]; then
 		COREDIR=$($LS_BIN -d $KDUMP_SAVEDIR/* 2>/dev/null)
 	fi
 else
-	if ! [ -d "$COREDIR" ]; then
+	if ! [[ -d "$COREDIR" ]]; then
 		echo "Invalid core directory specified! ($COREDIR)"
 		echo
 		exit -1
