Replace Novell with SUSE FTP upload servers

diff --git a/bin/getappcore b/bin/getappcore
--- a/bin/getappcore
+++ b/bin/getappcore
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-SVER='1.45_dev9.1'
+SVER='1.45_dev10.8'
 SDATE="2020 03 02"
 SNAME=$(basename $0)
 
@@ -39,7 +39,7 @@ SNAME=$(basename $0)
 # Overview:                                                             #
 #                                                                       #
 # This script is intended to ease the process of getting application    #
-# cores to an analyzable state by Novell Support.                       #
+# cores to an analyzable state by SUSE Technical Support.               #
 #                                                                       #
 # This script creates a tarball containing the specified application    #
 # core, and all libraries required to run the core'ing binary. This     #
@@ -73,8 +73,17 @@ SERVER_NAME=$(/bin/uname -n)
 SUSE_RELEASE="/etc/SuSE-release"
 OS_RELEASE="/etc/os-release"
 UPLOAD=0
-UPLOAD_URL="ftp://ftp.novell.com/incoming"
 VERBOSE=0
+
+SUSE_UPLOAD_NA_ASERVER='support-ftp.us.suse.com'
+SUSE_UPLOAD_EMEA_ASERVER='support-ftp.emea.suse.com'
+SUSE_UPLOAD_NA_HTTPS="https://${SUSE_UPLOAD_NA_ASERVER}/incoming/upload.php?appname=supportconfig&file={tarball}"
+SUSE_UPLOAD_NA_FTPES="ftps://${SUSE_UPLOAD_NA_ASERVER}/incoming"
+SUSE_UPLOAD_EMEA_HTTPS="https://${SUSE_UPLOAD_EMEA_ASERVER}/incoming/upload.php?appname=supportconfig&file={tarball}"
+SUSE_UPLOAD_EMEA_FTPES="ftps://${SUSE_UPLOAD_EMEA_ASERVER}/incoming"
+DEFAULT_HTTPS="${SUSE_UPLOAD_NA_HTTPS}"
+DEFAULT_FTPES="${SUSE_UPLOAD_NA_FTPES}"
+UPLOAD_TARGET="${DEFAULT_HTTPS}"
 
 #Required Binaries
 AWK_BIN=/usr/bin/awk
@@ -151,8 +160,9 @@ show_help() {
 	echo
 	echo "  -h              This screen"
 	echo "  -b [BINARY]     Binary which generated [COREFILE]"
-	echo "  -r [SR Number]  Novell Service Request number associated with this issue"
-	echo "  -u              Automatically upload archive to ftp.novell.com:/incoming"
+	echo "  -r [SR Number]  SUSE Service Request number associated with this issue"
+	echo "  -u              Automatically upload archive to the SUSE FTP server using HTTPS"
+	echo "  -f              Automatically upload archive to the SUSE FTP server using FTPES"
 	echo "  -v              Enable verbose messages"
 	echo
 	echo "For example:"
@@ -230,7 +240,7 @@ check_binaries()
 # Create the archive filename                               #
 # --------------------------------------------------------- #
 create_filename() {
-	CORE_ARCHIVE_NAME="$SERVER_NAME"_"$($BASENAME_BIN $COREFILE_BIN)_$($DATE_BIN +%y%m%d_%H%M)_appcore"
+	CORE_ARCHIVE_NAME="$SERVER_NAME"_"$($BASENAME_BIN $COREFILE_BIN)_$($DATE_BIN +%y%m%d_%H%M%S)_appcore"
 	if [ -z "$SR_NUM" ]; then
 		CORE_ARCHIVE_NAME="nts_${CORE_ARCHIVE_NAME}"
 	else
@@ -248,8 +258,8 @@ create_filename() {
 # ----------------------------------------------------------------- #
 create_opencoreini() {
 	# Strip double slashes and ././ from COREFILE and COREFILE_BIN
-	COREFILE_BIN_TMP=`echo "./${COREFILE_BIN#./}" | sed s#//*#/#g`
-	COREFILE_TMP=`echo "./${COREFILE#./}" | sed s#//*#/#g`
+	COREFILE_BIN_TMP=`echo "./${COREFILE_BIN#./}" | $SED_BIN s#//*#/#g`
+	COREFILE_TMP=`echo "./${COREFILE#./}" | $SED_BIN s#//*#/#g`
 	echo "# Generated by $SNAME v$SVER"				>  $OPENCORE_INI
 	echo "# Command line used: $CMDLINE"				>> $OPENCORE_INI
 	echo "# GDB environment:"					>> $OPENCORE_INI
@@ -330,14 +340,15 @@ create_archive() {
 	echo -n "Creating core archive... "
 	ORIGINAL_DIR=$PWD
 	cd $TMP_DIR
-	FINAL_ARCHIVE_NAME=$ARCHIVE_PATH/${CORE_ARCHIVE_NAME}.tbz
+	FINAL_ARCHIVE_FILE="${CORE_ARCHIVE_NAME}.tbz"
+	FINAL_ARCHIVE_NAME="${ARCHIVE_PATH}/${FINAL_ARCHIVE_FILE}"
 	verbose "Executing: $TAR_BIN -jhvcvf $FINAL_ARCHIVE_NAME $CORE_ARCHIVE_NAME 1>/dev/null 2>&1"
 	$TAR_BIN -jhvcvf $FINAL_ARCHIVE_NAME $CORE_ARCHIVE_NAME 1>/dev/null 2>&1
 	if [ -e $FINAL_ARCHIVE_NAME ]; then
 		echo "Done"
-		echo "        Created archive as:  $FINAL_ARCHIVE_NAME"
+		echo "+ Created archive as:  $FINAL_ARCHIVE_NAME"
 	else
-		echo "        Unable to create $FINAL_ARCHIVE_NAME!"
+		echo "+ Unable to create $FINAL_ARCHIVE_NAME!"
 	fi
 	cd $ORIGINAL_DIR
 }
@@ -347,22 +358,56 @@ create_archive() {
 # Upload the appcore archive to the designated ftp server   #
 # --------------------------------------------------------- #
 upload_archive() {
-        echo "Uploading Archive..."
+        echo "Uploading Archive... ${FINAL_ARCHIVE_FILE}"
+	UPLOAD_SERVICE=$(echo ${UPLOAD_TARGET} | cut -d: -f1)
+	ERRNO=255
+	verbose "UPLOAD_TARGET      = ${UPLOAD_TARGET}"
+	verbose "FINAL_ARCHIVE_FILE = ${FINAL_ARCHIVE_FILE}"
+	verbose "FINAL_ARCHIVE_NAME = ${FINAL_ARCHIVE_NAME}"
+	case $UPLOAD_SERVICE in
+	https)
+		echo "Protocol... HTTPS"
+		UPLOAD_URL=$($SED_BIN -e "s/{[Tt][Aa][Rr][Bb][Aa][Ll][Ll]}/${FINAL_ARCHIVE_FILE}/g" <<< ${UPLOAD_TARGET})
+		verbose "UPLOAD_URL         = $UPLOAD_URL"
+		verbose "Executing: $CURL_BIN -v -L -A SupportConfig -T ${FINAL_ARCHIVE_NAME} ${UPLOAD_URL}"
+		if (( $VERBOSE )); then
+			$CURL_BIN -v -L -A SupportConfig -T "${FINAL_ARCHIVE_NAME}" "${UPLOAD_URL}"
+			ERRNO=$?
+		else
+			$CURL_BIN -v -L -A SupportConfig -T "${FINAL_ARCHIVE_NAME}" "${UPLOAD_URL}" &> $GETAPPCORE_LOG
+			ERRNO=$?
+		fi
+		;;
+        ftps|ftpes)
+		echo "Protocol... FTPES"
+		UPLOAD_URL=$($SED_BIN -e 's/ftpes:/ftp:/g;s/ftps:/ftp:/g' <<< ${UPLOAD_TARGET})
+		verbose "UPLOAD_URL         = $UPLOAD_URL"
+		FTPES_OPTIONS="--ssl-reqd"
+		verbose "Executing: $CURL_BIN -#T ${FINAL_ARCHIVE_NAME} ${FTPES_OPTIONS} ${UPLOAD_URL}/${FINAL_ARCHIVE_FILE}"
+		if (( $VERBOSE )); then
+			$CURL_BIN -#T ${FINAL_ARCHIVE_NAME} ${FTPES_OPTIONS} ${UPLOAD_URL}/${FINAL_ARCHIVE_FILE}
+			ERRNO=$?
+		else
+			$CURL_BIN -#T ${FINAL_ARCHIVE_NAME} ${FTPES_OPTIONS} ${UPLOAD_URL}/${FINAL_ARCHIVE_FILE} &> $GETAPPCORE_LOG
+			ERRNO=$?
+		fi
+		;;
+	esac
 	echo
-	verbose "Executing: $CURL_BIN -sT $FINAL_ARCHIVE_NAME $UPLOAD_URL/$($BASENAME_BIN $FINAL_ARCHIVE_NAME)"
-	$CURL_BIN -sT $FINAL_ARCHIVE_NAME $UPLOAD_URL/$($BASENAME_BIN $FINAL_ARCHIVE_NAME)
-	if [ "$?" = "1" ]; then
-		echo "   Upload failed! Please upload the archive manually."
+	if (( $ERRNO )); then
+		echo "Upload status... FAILED"
+		echo
+		echo "Please upload the archive manually."
 	else
-		echo "   Upload successful!"
+		echo "Upload status... Success!"
 		echo
-		echo "   Please contact Novell Technical Services for assistance analyzing this core." 
-		echo "   If you already have an open Service Request, please update the SR with the"
-		echo "   name of the file which has just been uploaded:"
-		echo
-		echo "      $($BASENAME_BIN $FINAL_ARCHIVE_NAME)"
-		echo
+		echo "   Please contact SUSE Technical Support for assistance analyzing this core." 
+		echo "   If you already have an open Service Request, please update it with the"
+		echo "   archive name below."
 	fi
+	echo
+	echo "   Archive Name: ${FINAL_ARCHIVE_NAME}"
+	echo
 }
 
 
@@ -370,7 +415,7 @@ upload_archive() {
 # main ()                                                   #
 # Main script function                                      #
 # --------------------------------------------------------- #
-while getopts b:hr:uv opt
+while getopts b:hr:ufv opt
 do
 	case $opt in
 	\?)
@@ -385,6 +430,11 @@ do
 		;;
 	u)
 		UPLOAD=1
+		UPLOAD_TARGET="${DEFAULT_HTTPS}"
+		;;
+	f)
+		UPLOAD=1
+		UPLOAD_TARGET="${DEFAULT_FTPES}"
 		;;
 	v)
 		VERBOSE=1
@@ -395,6 +445,8 @@ do
 		;;
 	esac
 done
+
+show_title
 
 eval COREFILE=\$$OPTIND
 CMDLINE="$0 $*"
@@ -413,7 +465,6 @@ fi
 
 if [ ! -z $COREFILE -a -e $COREFILE ]; then
 	get_server_release
-	show_title
 
 	COREFILE=$($READLINK_BIN -f $COREFILE)
 	if [ -z $COREFILE_BIN ]; then
@@ -557,10 +608,8 @@ if [ ! -z $COREFILE -a -e $COREFILE ]; then
 		create_symlinks
 		create_archive
 
+		(( $UPLOAD )) && upload_archive
 		cleanup
-		if [ $UPLOAD -eq '1' ]; then
-			upload_archive
-		fi
 	fi
 else
 	if [ -z $COREFILE ]; then
