more descriptive verbose logging

diff --git a/bin/getappcore b/bin/getappcore
--- a/bin/getappcore
+++ b/bin/getappcore
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-SVER='1.47_dev26'
-SDATE="2020 03 05"
+SVER='1.47_dev30.7'
+SDATE="2020 03 06"
 SNAME=$(basename $0)
 
 # --------------------------------------------------------------------- #
@@ -125,7 +125,7 @@ UNIQ_BIN=/usr/bin/uniq
 WC_BIN=/usr/bin/wc
 WHICH_BIN=/usr/bin/which
 XARGS_BIN=/usr/bin/xargs
-ALL_BINS="$AWK_BIN $BASENAME_BIN $CAT_BIN $CHKBIN_BIN $CHMOD_BIN $COREDUMP_BIN $CUT_BIN $DATE_BIN $DIRNAME_BIN $DOS2UNIX_BIN $FIND_BIN \
+ALL_BINS="$AWK_BIN $BASENAME_BIN $CAT_BIN $CHKBIN_BIN $CHMOD_BIN $COREDUMP_BIN $CUT_BIN $DATE_BIN $DIRNAME_BIN $FIND_BIN \
 	$CURL_BIN $GDB_BIN $GREP_BIN $HEAD_BIN $LN_BIN $MKDIR_BIN $MV_BIN $READLINK_BIN $RM_BIN $RMDIR_BIN $RPM_BIN \
 	$SED_BIN $SORT_BIN $TAR_BIN $TEE_BIN $TR_BIN $UNAME_BIN $UNIQ_BIN $WC_BIN $WHICH_BIN $XARGS_BIN"
 
@@ -176,7 +176,8 @@ show_help() {
 	echo
 	echo "For example:"
 	echo 
-	echo "   $SNAME -ur 12345678 -b /bin/rpm /core.15832"
+	echo "   $SNAME -ur 00123456 -b /bin/rpm -j 2344"
+	echo "   $SNAME -ur 00123456 -b /bin/rpm /core.15832"
 	echo
 	echo "$SNAME version $SVER ($SDATE)"
 	echo
@@ -189,7 +190,7 @@ show_help() {
 # --------------------------------------------------------- #
 verbose() {
         if [[ $VERBOSE -eq '1' ]]; then
-                echo "-- $1"
+		[[ -z $1 ]] && echo || echo "-- $1"
         fi
 }
 
@@ -257,9 +258,11 @@ create_filename() {
 	else
 		CORE_ARCHIVE_NAME="nts_SR${SR_NUM}_${CORE_ARCHIVE_NAME}"
 	fi
+	verbose "Using archive name $CORE_ARCHIVE_NAME"
 	OPENCORE_INI=$GETAPPCORE_TMP_DIR/$CORE_ARCHIVE_NAME/opencore.ini
 	OPENCORE_SH=$GETAPPCORE_TMP_DIR/$CORE_ARCHIVE_NAME/opencore.sh
 	LOG_DIR=$GETAPPCORE_TMP_DIR/$CORE_ARCHIVE_NAME/logs
+	verbose "Making the log directory $LOG_DIR"
 	$MKDIR_BIN -p $LOG_DIR
 }
 
@@ -269,6 +272,7 @@ create_filename() {
 # ----------------------------------------------------------------- #
 create_opencoreini() {
 	# Strip double slashes and ././ from COREFILE and COREFILE_BIN
+	verbose "Creating file: $OPENCORE_INI"
 	COREFILE_BIN_TMP=`echo "./${COREFILE_BIN#./}" | $SED_BIN s#//*#/#g`
 	COREFILE_TMP=`echo "./${COREFILE#./}" | $SED_BIN s#//*#/#g`
 	echo "# Generated by $SNAME v$SVER"				>  $OPENCORE_INI
@@ -294,6 +298,7 @@ create_opencoreini() {
 # Create the opencore.sh script at the root of the archive  #
 # --------------------------------------------------------- #
 create_opencoresh() {
+	verbose "Creating file: $OPENCORE_SH"
 	echo "#!/bin/sh"								>  $OPENCORE_SH
 	echo "gdb --command=./$($BASENAME_BIN $OPENCORE_INI)"				>> $OPENCORE_SH
 	echo ""										>> $OPENCORE_SH
@@ -357,6 +362,7 @@ create_archive() {
 	cd $GETAPPCORE_TMP_DIR
 	FINAL_ARCHIVE_FILE="${CORE_ARCHIVE_NAME}.tbz"
 	FINAL_ARCHIVE_NAME="${ARCHIVE_PATH}/${FINAL_ARCHIVE_FILE}"
+	verbose ''
 	verbose "Executing: $TAR_BIN -jhvcvf $FINAL_ARCHIVE_NAME $CORE_ARCHIVE_NAME 1>/dev/null 2>&1"
 	$TAR_BIN -jhvcvf $FINAL_ARCHIVE_NAME $CORE_ARCHIVE_NAME 1>/dev/null 2>&1
 	if [ -e $FINAL_ARCHIVE_NAME ]; then
@@ -379,10 +385,15 @@ show_journal_coredumps() {
 	echo $CORENUM
 	if (( $CORENUM )); then
 		echo
-		echo "Newest coredump:"
-		$COREDUMP_BIN list -1
-		echo
-		echo "Use '$COREDUMP_BIN list' to see more."
+		if (( $VERBOSE )); then
+			$COREDUMP_BIN list
+		else
+			echo
+			echo "Most recent coredump:"
+			$COREDUMP_BIN list -1
+			echo
+			echo "Use '$COREDUMP_BIN list' to see more."
+		fi
 	fi
 	echo
 }
@@ -533,13 +544,13 @@ fi
 if [ ! -z $COREFILE -a -e $COREFILE ]; then
 	COREFILE=$($READLINK_BIN -f $COREFILE)
 	if [ -z $COREFILE_BIN ]; then
-		echo -n "Binary file not provided, trying to determine source binary using gdb... "
+		echo -n "Scanning core for binary file... "
 		COREFILE_BIN=`$GDB_BIN --core=$COREFILE --batch 2>/dev/null | $GREP_BIN "generated" | $CUT_BIN -d '\`'  -f 2| $CUT_BIN -d " " -f 1 | $CUT_BIN -d "'" -f 1 | $CUT_BIN -d ":" -f 1`
 		if [ ! -z "$COREFILE_BIN" ]; then
 			COREFILE_BIN=`$WHICH_BIN $COREFILE_BIN 2>/dev/null`
 		fi
 	else
-		echo -n "Binary file manually provided, confirming file type... "
+		echo -n "Validating binary file... "
 	fi
 	if ! [ -x $COREFILE_BIN ]; then
 		echo
@@ -547,6 +558,8 @@ if [ ! -z $COREFILE -a -e $COREFILE ]; then
 		echo "  ($COREFILE_BIN does not seem to be an executable!)"
 		echo "Please manually determine the binary, and execute the script again"
 		echo "using the '-b [CORE_BINARY] parameter."
+		echo
+		cleanup
 		exit -1
 	else
 		COREFILE_BIN=$($READLINK_BIN -f $COREFILE_BIN)
@@ -566,7 +579,7 @@ if [ ! -z $COREFILE -a -e $COREFILE ]; then
 		verbose "Chkbin result:   $CHKBIN_RESULT"
 
 		# Use GDB to build list of required libraries
-		echo -n "Building list of required libraries with gdb... " 
+		echo -n "Building list of required libraries... " 
 		echo "Libraries:" >> $GETAPPCORE_LOG
 		echo "----------" >> $GETAPPCORE_LOG
 		# Create temporary GDB command file
@@ -626,8 +639,8 @@ if [ ! -z $COREFILE -a -e $COREFILE ]; then
 		done < $GETAPPCORE_LOG
 		# Parse list of debug RPMs and add to log
 		echo $DBG_LIST | $TR_BIN " " \\n | $SORT_BIN | $UNIQ_BIN >> $GETAPPCORE_LOG
-		verbose ""
 		if (( $VERBOSE )); then
+			echo
 	                echo "                               ... Done"
 		else
 			echo " Done"
@@ -667,22 +680,25 @@ if [ ! -z $COREFILE -a -e $COREFILE ]; then
 		CHKBIN_LOG=$LOG_DIR/$(basename $CHKBIN_LOG)
 		GETAPPCORE_LOG=$LOG_DIR/$(basename $GETAPPCORE_LOG)
 
-		echo -n "Creating gdb startup files... "
+		(( $VERBOSE )) && { echo "Creating gdb startup files... "; echo; } || echo -n "Creating gdb startup files... "
 		create_opencoreini
 		create_opencoresh
-                echo "Done"
-
 		create_symlinks
+                (( $VERBOSE )) && { echo "                          ... Done"; echo; } || echo "Done"
+
 		create_archive
 
 		(( $UPLOAD )) && upload_archive
 		cleanup
 		echo
-		echo "Archive Name: ${FINAL_ARCHIVE_NAME}"
+		echo "Affected Binary: ${COREFILE_BIN}"
+		echo "Coredump File:   ${COREFILE}"
+		echo "Archive Name:    ${FINAL_ARCHIVE_NAME}"
+		(( $UPLOAD )) && echo "Upload Target:   ${UPLOAD_TARGET}"
 	fi
 else
 	if [ -z $COREFILE ]; then
-		echo "Required parameter COREFILE missing!"
+		echo "Required parameter -j PID or COREFILE missing!"
 	else
 		echo "Missing valid corefile!"
 	fi
